### PR TITLE
[WIP] Add gpuci build script

### PR DESCRIPTION
**Pull request by andersy005**

### CODE REVIEW

**Comment by andersy005** [comment]
rerun tests

**Comment by brittainhard** [comment]
run tests

**Comment by brittainhard** [comment]
run tests

**Comment by brittainhard** [comment]
In order for this to work, a github hook needs to be added linking to the gpuci server. The settings in [https://github.com/Quansight/dask_gdf](https://github.com/Quansight/dask_gdf) show how to do this. If it is still not working, make a comment on a PR saying either "run tests" or "rerun tests".

**Comment by scopatz** [comment]
I think an admin needs to do use the magic words

**Comment by mike-wendt** [comment]
run tests

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by kkraus14** [comment]
LGTM, will fix failing tests in a followup PR.

**Pull request merged**
